# Generated by Django 4.0.4 on 2022-07-28 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_category', models.CharField(choices=[('Electronics', (('CT', 'Computers & Tablets'), ('CP', 'Cameras & Photo'), ('HS', 'Home Surveillance Systems'), ('GA', 'Gaming'), ('CA', 'Cell Phones, Smart Watches & Accessories'), ('TV', 'TV, Video & Home Audio Electronics'))), ('Fashion', (('MN', 'Men'), ('WN', 'Women'), ('KD', 'Kids'))), ('Sports', (('CY', 'Cycling'), ('FI', 'Fitness, Running & Yoga'), ('OS', 'Outdoor Sports'), ('TG', 'Tactical & Duty Gear'), ('WS', 'Water Sports')))], default=None, max_length=2)),
                ('listing_title', models.CharField(max_length=100)),
                ('listing_content', models.TextField(max_length=300)),
                ('listing_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('listing_image_file', models.ImageField(null=True, upload_to='media/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_starting_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bid_current_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bid_start_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('bid_finish_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
