# Generated by Django 4.0.4 on 2022-07-21 00:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=100)),
                ('listing_content', models.TextField(max_length=300)),
                ('listing_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('listing_stock', models.IntegerField(default=0)),
                ('listing_status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable'), ('S', 'Sold out')], max_length=1)),
                ('listing_image_url', models.CharField(max_length=500, null=True)),
                ('listing_image_file', models.ImageField(null=True, upload_to='media/', verbose_name='')),
                ('listing_start_date', models.DateField(default=datetime.date(2022, 7, 20))),
                ('listing_end_date', models.DateField(default=datetime.date(2022, 7, 20))),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_starting_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bid_current_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bid_start_date_time', models.DateTimeField(default=datetime.date(2022, 7, 20))),
                ('bid_finish_date_time', models.DateTimeField(default=datetime.date(2022, 7, 20))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auctions.listing')),
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auctions.category')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_listings', to='auctions.category')),
                ('products', models.ManyToManyField(related_name='categories_listings', to='auctions.listing')),
            ],
            bases=('auctions.category', 'auctions.listing'),
        ),
    ]
