# Generated by Django 4.0.4 on 2022-07-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_watchlist_comments_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image_file',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
