# Generated by Django 4.0.4 on 2022-07-27 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_watchlist_comments_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='CategoryListing',
        ),
    ]
