# Generated by Django 4.0.4 on 2022-08-10 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_finish_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
