# Generated by Django 4.0.4 on 2022-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_bid_finish_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_finish_date_time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_start_date_time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_starting_value',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_finished',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1),
        ),
    ]
