# Generated by Django 4.0.4 on 2022-09-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_finished',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1, null=True),
        ),
    ]
